CREATE PROCEDURE [dbo].SeedCourses
	
AS
insert into dbo.Courses([Code], [Title]) values('ACON-SAPFCMI', 'ACONS SAP FICO-Cross Module Integration')
insert into dbo.Courses([Code], [Title]) values('ACON-SAPFIAP', 'ACONS SAP FICO-Accounts Payable')
insert into dbo.Courses([Code], [Title]) values('ACON-SAPFIAR', 'ACONS SAP FICO-Accounts Receivables')
insert into dbo.Courses([Code], [Title]) values('ACON-SAPFICO', 'ACONS SAP FICO TRAINING')
insert into dbo.Courses([Code], [Title]) values('ACON-SAPSD', 'ACONS SAP SD TRAINING')
insert into dbo.Courses([Code], [Title]) values('AGL1001', 'Programming Scala')
insert into dbo.Courses([Code], [Title]) values('AGL1002', 'Programming with Groovy')
insert into dbo.Courses([Code], [Title]) values('AGL1003', 'Programming with Grails')
insert into dbo.Courses([Code], [Title]) values('AGL1004', 'Programming with Python')
insert into dbo.Courses([Code], [Title]) values('AGL1005', 'Programming with Django')
insert into dbo.Courses([Code], [Title]) values('AGL1006', 'Object Oriented Programming with Ruby')
insert into dbo.Courses([Code], [Title]) values('AGL1007', 'Intro to Ruby on Rails')
insert into dbo.Courses([Code], [Title]) values('AGL1008', 'Introduction to Groovy')
insert into dbo.Courses([Code], [Title]) values('AGL1009', 'Introduction to Groovy on Grails')
insert into dbo.Courses([Code], [Title]) values('AGL1010', 'Introduction to Scala Programming')
insert into dbo.Courses([Code], [Title]) values('AGL1011', 'Play framework for Scala Developers_AGL1011')
insert into dbo.Courses([Code], [Title]) values('AGL1012', 'System and Network Prog using Python')
insert into dbo.Courses([Code], [Title]) values('AGL1013', 'Cucumber - BDD')
insert into dbo.Courses([Code], [Title]) values('AGL1014', 'Introduction to Python and Django')
insert into dbo.Courses([Code], [Title]) values('AGL1015', 'BDD using Jbehave')
insert into dbo.Courses([Code], [Title]) values('APP1009', 'Apple: Objective-C')
insert into dbo.Courses([Code], [Title]) values('APP1010', 'Apple: Cocoa')
insert into dbo.Courses([Code], [Title]) values('APP1011', 'Apple: Introduction to Mac Technologies')
insert into dbo.Courses([Code], [Title]) values('APP1012', 'Apple: iOS Programming')
insert into dbo.Courses([Code], [Title]) values('APP1020', 'Apple: Advanced Cocoa')
insert into dbo.Courses([Code], [Title]) values('APP1022', 'Apple: Advanced iOS Programming PART I')
insert into dbo.Courses([Code], [Title]) values('APP1026', 'Apple:Advanced UX Design & Engineering')
insert into dbo.Courses([Code], [Title]) values('APP1027', 'Mobile:Human Interface Guidelines')
insert into dbo.Courses([Code], [Title]) values('AR01', 'Architecture description using IEE1471')
insert into dbo.Courses([Code], [Title]) values('AR03', 'Non Functional Requirements and ISO 9126')
insert into dbo.Courses([Code], [Title]) values('BASIS_DEBUG', 'ABAP debugging n basics for Funct CONs')
insert into dbo.Courses([Code], [Title]) values('BDA3', 'Introduction to Business Data Analytics')
insert into dbo.Courses([Code], [Title]) values('BIBOB', 'ER using Business Objects_BIBOB')
insert into dbo.Courses([Code], [Title]) values('BICOG', 'ER using Cognos_BICOG')
insert into dbo.Courses([Code], [Title]) values('BIDBRD', 'Enterprise Dashboards_BIDBRD')
insert into dbo.Courses([Code], [Title]) values('BIDWH', 'Building Datawarehouse_BIDWH')
insert into dbo.Courses([Code], [Title]) values('BIERWIN', 'Data Modeling using Erwin_BIERWIN')
insert into dbo.Courses([Code], [Title]) values('BIINF', 'ETL using Informatica_BIINF')
insert into dbo.Courses([Code], [Title]) values('BIIS08', 'ETL using SSIS 2008_BIIS08')
insert into dbo.Courses([Code], [Title]) values('BIRFPROI', 'RFP to ROI_BIRFPROI')
insert into dbo.Courses([Code], [Title]) values('BIRS08', 'ER using SSRS 2008_BIRS08')
insert into dbo.Courses([Code], [Title]) values('BISQL08', 'Introduction to SQL 2008 database_BISQL08')
insert into dbo.Courses([Code], [Title]) values('BISSAS08', 'SQL Server Analysis Services')
insert into dbo.Courses([Code], [Title]) values('BISSIS08', 'SQL Server Intergration Services')
insert into dbo.Courses([Code], [Title]) values('BISSRS08', 'SQL Server Reporting Services')
insert into dbo.Courses([Code], [Title]) values('BS001', 'Enterprise Functions ? Marketing')
insert into dbo.Courses([Code], [Title]) values('BS002', 'Enterprise Functions Manufacturing')
insert into dbo.Courses([Code], [Title]) values('BS003', 'Enterprise Functions Finance')
insert into dbo.Courses([Code], [Title]) values('BS004', 'Enterprise Functions HRM')
insert into dbo.Courses([Code], [Title]) values('BS005', 'Business Process')
insert into dbo.Courses([Code], [Title]) values('BS006', 'Enterprise IT Management')
insert into dbo.Courses([Code], [Title]) values('BS007', 'Business Metrics, KPIs and Dashboards')
insert into dbo.Courses([Code], [Title]) values('BS008', 'Strategic Management')
insert into dbo.Courses([Code], [Title]) values('BS011', 'Consulting ? Generic Perspective')
insert into dbo.Courses([Code], [Title]) values('BS012', 'Enterprise Functions Marketing')
insert into dbo.Courses([Code], [Title]) values('DataStage', 'ETL Using DataStage_DataStage')
insert into dbo.Courses([Code], [Title]) values('DB1001', 'Advanced SQL Server 2008 Development')
insert into dbo.Courses([Code], [Title]) values('DB1007', 'Advanced DB2 Application Programming')
insert into dbo.Courses([Code], [Title]) values('DB135', 'TERADATA_DB135')
insert into dbo.Courses([Code], [Title]) values('DB151', 'Intro to Enterprise mainframe prodn envi')
insert into dbo.Courses([Code], [Title]) values('DB153', 'DB2 Version 9 Features')
insert into dbo.Courses([Code], [Title]) values('DB154', 'DB2 v9 performance features')
insert into dbo.Courses([Code], [Title]) values('DB155', 'IDMS Fundamentals')
insert into dbo.Courses([Code], [Title]) values('DB162', 'DB2 SQL Stored Procedures on z/OS')
insert into dbo.Courses([Code], [Title]) values('DB164', 'Oracle SQL expert')
insert into dbo.Courses([Code], [Title]) values('DB165', 'Intro to PL/SQL')
insert into dbo.Courses([Code], [Title]) values('DB166', 'Adv Concepts in IMS DB on Mainframes')
insert into dbo.Courses([Code], [Title]) values('DB170', 'SQL Enhancements in DB2 V8 for Z/OS')
insert into dbo.Courses([Code], [Title]) values('DB171', 'SQL Tuning (Oracle 10g)')
insert into dbo.Courses([Code], [Title]) values('DB172', 'Basic Database Security')
insert into dbo.Courses([Code], [Title]) values('DB173', 'Secure Application Development in PL/SQL')
insert into dbo.Courses([Code], [Title]) values('DB174', 'Oracle Architecture')
insert into dbo.Courses([Code], [Title]) values('DB175', 'DB Tuning')
insert into dbo.Courses([Code], [Title]) values('DB177', 'Introduction to Data Structures')
insert into dbo.Courses([Code], [Title]) values('DB183', 'Oracle 11g New Features')
insert into dbo.Courses([Code], [Title]) values('DB184', 'Overview of IDMS')
insert into dbo.Courses([Code], [Title]) values('DB189', 'PL/SQL Tuning Best Practices')
insert into dbo.Courses([Code], [Title]) values('DB197', 'Reporting using BO_DB197')
insert into dbo.Courses([Code], [Title]) values('DB210', 'Microstrategy_DB210')
insert into dbo.Courses([Code], [Title]) values('DB211', 'Datamining Using Weka_DB211')
insert into dbo.Courses([Code], [Title]) values('DB213', 'Reporting using BIRT_DB213')
insert into dbo.Courses([Code], [Title]) values('DB221', 'Cloud - Big Data')
insert into dbo.Courses([Code], [Title]) values('DB226', 'Introduction to DB2 Catalogs')
insert into dbo.Courses([Code], [Title]) values('DB230', 'Data Mining_DB230')
insert into dbo.Courses([Code], [Title]) values('DB232', 'Data analysis and metric management')
insert into dbo.Courses([Code], [Title]) values('DB233', 'Multi-dimensional Data Modeling concepts')
insert into dbo.Courses([Code], [Title]) values('DB234', 'Pentaho Data Integration_DB234')
insert into dbo.Courses([Code], [Title]) values('DB235', 'Introduction to PosgreSQL')
insert into dbo.Courses([Code], [Title]) values('DB240', 'IBM Data Studio v 3.1 Features')
insert into dbo.Courses([Code], [Title]) values('DB243', 'Introduction to DB2 LUW')
insert into dbo.Courses([Code], [Title]) values('DB244', 'Oracle Grid Architecture 11g')
insert into dbo.Courses([Code], [Title]) values('DB245', 'Oracle Reports 11g')
insert into dbo.Courses([Code], [Title]) values('DB246', 'Oracle Forms 11g')
insert into dbo.Courses([Code], [Title]) values('DB247', 'Emerging trends in BI')
insert into dbo.Courses([Code], [Title]) values('DB249', 'Introduction to Splunk')
insert into dbo.Courses([Code], [Title]) values('DB251', 'Intro to Splunk Usage')
insert into dbo.Courses([Code], [Title]) values('DB253', 'Database Design & Implementation - MySQL')
insert into dbo.Courses([Code], [Title]) values('DB256', 'Catalog Statistics for DB2 Performance')
insert into dbo.Courses([Code], [Title]) values('DB259', 'Introduction to PLpgSql')
insert into dbo.Courses([Code], [Title]) values('DB267', 'Master in Oracle Programming with PL_SQL')
insert into dbo.Courses([Code], [Title]) values('DB268', 'Advance PL_SQL Programming Package')
insert into dbo.Courses([Code], [Title]) values('DB269', 'Oracle pl/sql performance tuning')
insert into dbo.Courses([Code], [Title]) values('DB270', 'App development using Oracle forms')
insert into dbo.Courses([Code], [Title]) values('DB272', 'Oracle 12c New Features')
insert into dbo.Courses([Code], [Title]) values('DB273', 'BMC Catalog Manager')
insert into dbo.Courses([Code], [Title]) values('DB274', 'Intro to MariaDB')
insert into dbo.Courses([Code], [Title]) values('DB33', 'SQL server tuning')
insert into dbo.Courses([Code], [Title]) values('DB48', 'Overview of DB2')
insert into dbo.Courses([Code], [Title]) values('DB71', 'Additional DB2/400 concepts')
insert into dbo.Courses([Code], [Title]) values('DB74', 'DB2- Application Tuning Techniques')
insert into dbo.Courses([Code], [Title]) values('DB75', 'Embedded SQL')
insert into dbo.Courses([Code], [Title]) values('DB76', 'iSeries Windows Integration')
insert into dbo.Courses([Code], [Title]) values('DB77', 'DB2 UDB Fundamentals')
insert into dbo.Courses([Code], [Title]) values('DB78', 'DB2 Tuning')
insert into dbo.Courses([Code], [Title]) values('DB80', 'SQL Server 2005 Tuning')
insert into dbo.Courses([Code], [Title]) values('DB85', 'Overview of IMS DB on Mainframes_DB85')
insert into dbo.Courses([Code], [Title]) values('DB88BI', 'Intro. To BI Framework_DB88BI')
insert into dbo.Courses([Code], [Title]) values('DB89BI', 'Multi-dimensional Data Modeling_DB89BI')
insert into dbo.Courses([Code], [Title]) values('DB96', 'DB2 High Performance and Tuning')
insert into dbo.Courses([Code], [Title]) values('DB97', 'OBIEE 11g_DB97')

RETURN 0