CREATE PROCEDURE [dbo].SeedRoles
	
AS
insert into dbo.Roles([Title], [Level]) values('Group Project Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Unit Client Solution Head', '7')
insert into dbo.Roles([Title], [Level]) values('Technology Lead', '5')
insert into dbo.Roles([Title], [Level]) values('Senior Client Solution Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Product Technical Architect', '6')
insert into dbo.Roles([Title], [Level]) values('Industry Principal', '7')
insert into dbo.Roles([Title], [Level]) values('Engineering Analyst', '4')
insert into dbo.Roles([Title], [Level]) values('Test Analyst', '4')
insert into dbo.Roles([Title], [Level]) values('Systems Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Project Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Engineering Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Regional Manager - IT Service', '6')
insert into dbo.Roles([Title], [Level]) values('Systems Engineer Trainee', '3')
insert into dbo.Roles([Title], [Level]) values('Technology Platform Analyst', '4')
insert into dbo.Roles([Title], [Level]) values('Technical Test Lead', '5')
insert into dbo.Roles([Title], [Level]) values('Senior Project Manager - Engineering', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Project Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Practice Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Account Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Consultant - Infrastructure Management', '5')
insert into dbo.Roles([Title], [Level]) values('Principal Technology Architect', '7')
insert into dbo.Roles([Title], [Level]) values('Senior Member - Education and Research', '4')
insert into dbo.Roles([Title], [Level]) values('Associate Consultant', '4')
insert into dbo.Roles([Title], [Level]) values('Technology Architect', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Systems Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Location Manager - IT Service', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Principal - Advanced Engineering', '7')
insert into dbo.Roles([Title], [Level]) values('Product Technical Lead', '5')
insert into dbo.Roles([Title], [Level]) values('Group Project Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Senior Unit Planning and Assurance Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Delivery Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Secretary', '3')
insert into dbo.Roles([Title], [Level]) values('Principal Consultant', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Manager - Unit Planning and Assurance', '6')
insert into dbo.Roles([Title], [Level]) values('Unit Planning and Assurance Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Engineering Lead', '5')
insert into dbo.Roles([Title], [Level]) values('Senior Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Principal Consultant - Advanced Engineering', '7')
insert into dbo.Roles([Title], [Level]) values('Principal Product Architect', '7')
insert into dbo.Roles([Title], [Level]) values('Senior Associate Consultant', '4')
insert into dbo.Roles([Title], [Level]) values('Senior Technical Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Test Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Technology Analyst', '4')
insert into dbo.Roles([Title], [Level]) values('Research Analyst', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Engineering Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Executive - Facilities', '3')
insert into dbo.Roles([Title], [Level]) values('Operations Executive', '2')
insert into dbo.Roles([Title], [Level]) values('Senior Technology Architect', '6')
insert into dbo.Roles([Title], [Level]) values('Technology Lead - Engineering', '5')
insert into dbo.Roles([Title], [Level]) values('Consultant', '5')
insert into dbo.Roles([Title], [Level]) values('Lead Consultant - Advanced Engineering', '6')
insert into dbo.Roles([Title], [Level]) values('Account Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Analyst - Planning and Assurance', '4')
insert into dbo.Roles([Title], [Level]) values('Senior Product Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Client Solution Lead', '5')
insert into dbo.Roles([Title], [Level]) values('Senior Secretary', '3')
insert into dbo.Roles([Title], [Level]) values('Consultant - Advanced Engineering', '5')
insert into dbo.Roles([Title], [Level]) values('Client Solution Manager', '6')
insert into dbo.Roles([Title], [Level]) values('Lead Consultant', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Consultant', '5')
insert into dbo.Roles([Title], [Level]) values('Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Information Security Engineer', '3')
insert into dbo.Roles([Title], [Level]) values('Associate Business Analyst', '3')
insert into dbo.Roles([Title], [Level]) values('Manager - Unit Planning and Assurance', '6')
insert into dbo.Roles([Title], [Level]) values('Senior Consultant - Infrastructure Management', '5')
insert into dbo.Roles([Title], [Level]) values('Principal Consultant - Advanced Engineering', '6')
insert into dbo.Roles([Title], [Level]) values('Principal - Enterprise Applications', '6')
insert into dbo.Roles([Title], [Level]) values('Lead Consultant - Infrastructure Management', '6')
insert into dbo.Roles([Title], [Level]) values('Lead - Planning and Assurance', '5')
insert into dbo.Roles([Title], [Level]) values('Senior Delivery Manager', '7')
insert into dbo.Roles([Title], [Level]) values('Testing Executive', '2')
insert into dbo.Roles([Title], [Level]) values('Technical Manager', '6')

RETURN 0