CREATE PROCEDURE [dbo].SeedLocations
	
	
AS
	insert into dbo.Locations([Code], [Title]) values('ATLANTA', 'ATLANTA')
insert into dbo.Locations([Code], [Title]) values('Basel', 'ZURICH')
insert into dbo.Locations([Code], [Title]) values('BASKINGRIDGE', 'Basking Ridge')
insert into dbo.Locations([Code], [Title]) values('BBSR1STP', 'BHUBANESWAR')
insert into dbo.Locations([Code], [Title]) values('BBSR2STP', 'Bhubaneswar')
insert into dbo.Locations([Code], [Title]) values('BELLEVUE', 'Bellevue')
insert into dbo.Locations([Code], [Title]) values('BENTONVILLE', 'Bentonville')
insert into dbo.Locations([Code], [Title]) values('BLRJPTowers', 'Bangalore')
insert into dbo.Locations([Code], [Title]) values('BLRMNCBLD', 'Bangalore')
insert into dbo.Locations([Code], [Title]) values('BRBELOHORI01', 'NOVA LIMA-MG')
insert into dbo.Locations([Code], [Title]) values('BrisbaneIL', 'Brisbane')
insert into dbo.Locations([Code], [Title]) values('CANARY WHARF', 'LONDON')
insert into dbo.Locations([Code], [Title]) values('CHARLOTTE', 'CHARLOTTE')
insert into dbo.Locations([Code], [Title]) values('CHD_SEZ', 'CHANDIGARH')
insert into dbo.Locations([Code], [Title]) values('CHD_STP', 'CHANDIGARH')
insert into dbo.Locations([Code], [Title]) values('CHENNAISTP', 'CHENNAI')
insert into dbo.Locations([Code], [Title]) values('CHICAGO', 'Lisle')
insert into dbo.Locations([Code], [Title]) values('CHICAGODC', 'Lisle')
insert into dbo.Locations([Code], [Title]) values('FRANCE', 'PARIS')
insert into dbo.Locations([Code], [Title]) values('FRANKFURT', 'Frankfurt')
insert into dbo.Locations([Code], [Title]) values('Glastonbury', 'Glastonbury')
insert into dbo.Locations([Code], [Title]) values('HINJ1STP', 'PUNE')
insert into dbo.Locations([Code], [Title]) values('HINJ2STP', 'PUNE')
insert into dbo.Locations([Code], [Title]) values('HINJ3STP', 'PUNE')
insert into dbo.Locations([Code], [Title]) values('HOUSTON', 'Houston')
insert into dbo.Locations([Code], [Title]) values('HYD1STP', 'Hyderabad')
insert into dbo.Locations([Code], [Title]) values('HYD2STP', 'Hyderabad')
insert into dbo.Locations([Code], [Title]) values('HYDSEZ_Unit2', 'Hyderabad')
insert into dbo.Locations([Code], [Title]) values('HYDSEZUnit3', 'Hyderabad')
insert into dbo.Locations([Code], [Title]) values('HYDSEZUNT1', 'Hyderabad')
insert into dbo.Locations([Code], [Title]) values('INFCITYBBU', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYCP', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYKEC', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK1', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK2', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK3', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK4', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK5', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('INFCITYPRK6', 'BANGALORE')
insert into dbo.Locations([Code], [Title]) values('MADRID', 'Madrid')
insert into dbo.Locations([Code], [Title]) values('MANG2STP', 'MANGALORE')
insert into dbo.Locations([Code], [Title]) values('MANGSEZ', 'MANGALORE')
insert into dbo.Locations([Code], [Title]) values('MANGSEZUnit2', 'MANGALORE')
insert into dbo.Locations([Code], [Title]) values('MCity', 'CHENNAI')
insert into dbo.Locations([Code], [Title]) values('MCITYUNITII', 'CHENNAI')
insert into dbo.Locations([Code], [Title]) values('MELBOURNE', 'MELBOURNE')
insert into dbo.Locations([Code], [Title]) values('Milwaukee', 'Milwaukee')
insert into dbo.Locations([Code], [Title]) values('Minnesota', 'Minnesota')
insert into dbo.Locations([Code], [Title]) values('Montreal', 'Montreal')
insert into dbo.Locations([Code], [Title]) values('MX_Monterrey', 'Monterrey')
insert into dbo.Locations([Code], [Title]) values('MYSORE1STP', 'Mysore')
insert into dbo.Locations([Code], [Title]) values('MYSORE2STP', 'Mysore')
insert into dbo.Locations([Code], [Title]) values('MYSSEZ_UNIT1', 'Mysore')
insert into dbo.Locations([Code], [Title]) values('MYSSEZ_Unit2', 'Mysore')
insert into dbo.Locations([Code], [Title]) values('NEWARK', 'Newark(CA)')
insert into dbo.Locations([Code], [Title]) values('NEWJERSY', 'Bridgewater')
insert into dbo.Locations([Code], [Title]) values('NEWYORK', 'NEW YORK')
insert into dbo.Locations([Code], [Title]) values('PHOENIX', 'Phoenix')

RETURN 0
