// <auto-generated />
namespace efAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtables_initialTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtables_initialTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201505141640205_addtables_initialTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
