// <auto-generated />
namespace efAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterCourse_addfk_training : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterCourse_addfk_training));
        
        string IMigrationMetadata.Id
        {
            get { return "201505151350082_alterCourse_addfk_training"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
