// <auto-generated />
namespace efAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterTable_Roles_col_level : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterTable_Roles_col_level));
        
        string IMigrationMetadata.Id
        {
            get { return "201505150224061_alterTable_Roles_col_level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
