CREATE TABLE [import].[Employees] (
    [Emp Name]                            NVARCHAR (255) NULL,
    [Emp No]                              FLOAT (53)     NULL,
    [Emp Mail ID]                         NVARCHAR (255) NULL,
    [Emp PU]                              NVARCHAR (255) NULL,
    [Emp DU]                              NVARCHAR (255) NULL,
    [Emp Base Location]                   NVARCHAR (255) NULL,
    [Emp Base City]                       NVARCHAR (255) NULL,
    [Joining Date (Current Legal Entity)] DATETIME       NULL,
    [Joining Date (Infosys Group)]        NVARCHAR (255) NULL,
    [Role Capability]                     NVARCHAR (255) NULL,
    [Emp Current Location]                NVARCHAR (255) NULL,
    [Emp Current City]                    NVARCHAR (255) NULL,
    [DU Head for Emp DU]                  FLOAT (53)     NULL,
    [DU Head Name for Emp DU]             NVARCHAR (255) NULL,
    [Project Code]                        NVARCHAR (255) NULL,
    [Master Project Code]                 NVARCHAR (255) NULL,
    [Project Practice Line ]              NVARCHAR (255) NULL,
    [Customer Code]                       NVARCHAR (255) NULL,
    [Master Customer Code]                NVARCHAR (255) NULL,
    [Onsite/Offshore]                     NVARCHAR (255) NULL,
    [From Date]                           DATETIME       NULL,
    [To Date]                             DATETIME       NULL,
    [Allocated Country]                   NVARCHAR (255) NULL,
    [Allocated State]                     NVARCHAR (255) NULL,
    [Allocated City]                      NVARCHAR (255) NULL,
    [Project Type]                        NVARCHAR (255) NULL,
    [Billing Type]                        NVARCHAR (255) NULL,
    [Reporting To Emp No]                 FLOAT (53)     NULL,
    [Reporting To Emp Name]               NVARCHAR (255) NULL,
    [Reporting To Mail Id]                NVARCHAR (255) NULL,
    [Proj Remarks]                        NVARCHAR (255) NULL,
    [Unit Code]                           NVARCHAR (255) NULL,
    [Project DM ]                         FLOAT (53)     NULL,
    [Project DM MailID]                   NVARCHAR (255) NULL,
    [Emp Exp In Infosys ]                 NVARCHAR (255) NULL,
    [Emp Prev Exp ]                       NVARCHAR (255) NULL,
    [Emp Total Exp]                       NVARCHAR (255) NULL,
    [Total Exp in Years]                  FLOAT (53)     NULL,
    [Appl Code]                           NVARCHAR (255) NULL,
    [Service Code]                        NVARCHAR (255) NULL,
    [Activity Code]                       NVARCHAR (255) NULL,
    [Tech Code]                           NVARCHAR (255) NULL,
    [Tech Category]                       NVARCHAR (255) NULL,
    [Marketing Branch Code]               NVARCHAR (255) NULL,
    [Proj DU Code]                        NVARCHAR (255) NULL,
    [Project DU Head]                     FLOAT (53)     NULL,
    [Project DUHead Name]                 NVARCHAR (255) NULL,
    [Project SDM]                         FLOAT (53)     NULL,
    [Project SDM MailId]                  NVARCHAR (255) NULL,
    [Proj DevCentre Code]                 NVARCHAR (255) NULL,
    [HR Remarks]                          NVARCHAR (255) NULL,
    [Job Band]                            NVARCHAR (255) NULL,
    [Personal Band]                       NVARCHAR (255) NULL,
    [Customer Portfolio]                  NVARCHAR (255) NULL,
    [PartTimeEmployee]                    NVARCHAR (255) NULL,
    [ProgramCode]                         NVARCHAR (255) NULL,
    [TrackCode]                           NVARCHAR (255) NULL,
    [EmployeeCompany]                     NVARCHAR (255) NULL,
    [Employee Budgeting Unit]             NVARCHAR (255) NULL,
    [Project Budgeting Unit]              NVARCHAR (255) NULL,
    [Project Company]                     NVARCHAR (255) NULL,
    [Project Source Company]              NVARCHAR (255) NULL,
    [Employee Attribute]                  NVARCHAR (255) NULL,
    [Emp Date Of Birth]                   NVARCHAR (255) NULL,
    [Emp Gender]                          NVARCHAR (255) NULL,
    [Group Master Project Code]           NVARCHAR (255) NULL,
    [Employee Competency]                 NVARCHAR (255) NULL,
    [Talent Status]                       NVARCHAR (255) NULL,
    [Employee Bench Type]                 NVARCHAR (255) NULL,
    [EmployeeSkills]                      NVARCHAR (255) NULL
);

